name: vk_native_client
description: Native client to be used in vishwakarma app
version: 0.0.3
homepage: "https://github.com/Code-Vedas/vk-native-client"

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.codevedas.vk_native_client
        pluginClass: VkNativeClientPlugin
      ios:
        pluginClass: VkNativeClientPlugin
      linux:
        pluginClass: VkNativeClientPlugin
      macos:
        pluginClass: VkNativeClientPlugin
      windows:
        pluginClass: VkNativeClientPluginCApi
      web:
        pluginClass: VkNativeClientWeb
        fileName: vk_native_client_web.dart
