name: cv_native_client
description: Native client to access platform specific features like clipboard, platform version, etc.
version: 1.0.0
homepage: "https://github.com/Code-Vedas/cv-native-client"
repository: "https://github.com/Code-Vedas/cv-native-client"
documentation: "https://github.com/Code-Vedas/cv-native-client"
issue_tracker: "https://github.com/Code-Vedas/cv-native-client/issues"
topics:
  - clipboard

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  js: ">=0.6.7 <0.8.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.codevedas.cv_native_client
        pluginClass: CvNativeClientPlugin
      ios:
        pluginClass: CvNativeClientPlugin
      linux:
        pluginClass: CvNativeClientPlugin
      macos:
        pluginClass: CvNativeClientPlugin
      windows:
        pluginClass: CvNativeClientPluginCApi
      web:
        pluginClass: CvNativeClientWeb
        fileName: web/cv_native_client_web.dart
